config/routes.rb
Rails.application.routes.draw do

  get 'sessions/login'

  resources :authors
  get '/search', to: 'sessions#search'
  post 'search', to: 'sessions#post_search'

  get '/login', to: 'sessions#login'
  post 'login', to: 'sessions#post_login'
  delete '/logout',  to: 'sessions#destroy'

  resources :books
  root "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :book
  validates :name, presence: true, length: {maximum: 50}

end

app/models/book.rb
class Book < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
	validates :title, presence: true, length: {maximum: 100}
	validates :publisher, presence: true, length: {maximum: 50}
	validates :ISBN, presence: true, uniqueness: true
	validates :publish_date, presence: true
	has_many :authors, dependent: :destroy
	accepts_nested_attributes_for  :authors


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_admin
      unless logged_in?
      	flash[:danger]="log in as admin first!"
        redirect_to login_url
      end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_admin, only: [:create, :destroy, :update, :new, :edit]


  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author}
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author}
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :book_id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_admin, only: [:create, :destroy, :update, :new, :edit]

  # GET /books
  # GET /books.json
  def index
    @books = Book.paginate(page: params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.authors.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book }
        format.json { render :show, status: :created, location: @book }
        flash[:success] ="Book was successfully created."
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params) 
        format.html { redirect_to @book}
        format.json { render :show, status: :ok, location: @book }
        flash[:success]="Book was successfully updated."
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
      flash[:success]="Book was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :publisher, :ISBN, :publish_date, :authors_attributes => [:id, :name])
    end

    def author_params
      params.require(:book).permit(:id, :name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def search
  	if @book_items==nil
  		@book_items=[]
  	end
  end

  def post_search
  	if params[:session][:search]== "title"
      if params[:session][:search_title]==""
        flash[:danger]="title can't be empty!"  
      else
        @books= books_by_title params[:session][:search_title]

      end    

  	elsif params[:session][:search]== "author"
      if params[:session][:search_author]==""
        flash[:danger]="author can't be empty!" 
      else 
        @books= books_by_author params[:session][:search_author]
      end
    
  	else
      if params[:session][:search_publisher]==""
        flash[:danger]="publisher can't be empty!" 
      else
        @books= books_by_publisher params[:session][:search_publisher]
      end
      
  	end


    if !@books.nil?
      @book_items= @books.paginate(page: params[:page])
      render 'search'
    else
      @book_items=[]
      redirect_to search_path
    end
  	
  end

  def books_by_title (title)
    Book.where("title like ?", "%#{title}%")  
  end

  def books_by_author (author)
    book_ids=Author.where("name like ?", "%#{author}%").select(:book_id)
    Book.where("id IN (?)", book_ids )  
  end

  def books_by_publisher (publisher)
    Book.where("publisher like ?", "%#{publisher}%")  
  end



  def login
  end

  def post_login
    if(params[:session][:email]=="") || (params[:session][:password]=="")
      flash.now[:danger]="Email and password can't be empty!."
      render 'login'
    elsif (params[:session][:email]== ENV['EMAIL'])&&(params[:session][:password]== ENV['PASSWORD'] )
      log_in
      redirect_to root_url
    else
      flash.now[:danger]="Invalid email and pasword!."
      render 'login'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in
    	session[:admin] = true
  	end

  	def logged_in?
		session[:admin]
	end

	def log_out
		session.delete(:admin)
	end	    
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :author_name %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id, id: :author_book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.book %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Book:</strong>
  <%= @author.book %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_book.html.erb
<li id="book-<%= book.id %>">
  <span class="title"><%= book.title %></span>
  <span class="publisher"><%= book.publisher %></span>
  <span class="timestamp">
    Publishd <%= time_ago_in_words(book.publish_date) %> ago.
  </span>
  <span class="show"><%= link_to 'Show', book%> </span>
  <%if logged_in?%>
  	<span class="destroy"><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></span>
  <%end%>

</li>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :publisher %>
  <%= f.text_field :publisher, class: 'form-control' %>

  <%= submit_tag "Add Author", :type => 'button', :id => 'addAuthor', 
          :onclick => 'addAuthorField()' %> 
   
 
  <div id="authorHeader" style="display:none">Author:  </div>
   
 
  <ul id="myList">
  </ul>

  <%= f.label :ISBN %>
  <%= f.text_field :ISBN, class: 'form-control' %>

  <%= f.label :publish_date %>
  <%= f.datetime_select :publish_date, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<%= form_for(@book) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :title %>
	  <%= f.text_field :title, class: 'form-control' %>

	  <%= f.label :publisher %>
	  <%= f.text_field :publisher, class: 'form-control' %>

	  
	  	<%= f.fields_for :authors do |a|%>
	  		<%= a.label :author %>
	  		<%= a.text_field :name, class: 'form-control' %>
	  	<%end%>

	  <%= submit_tag "Add Author", :type => 'button', :id => 'addAuthor', 
	          :onclick => 'addAuthorField()' %> 
	   
	 
	  <div id="authorHeader" style="display:none">Author:  </div>
	   
	 
	  <ul id="myList">
	  </ul>

	  <%= f.label :ISBN %>
	  <%= f.text_field :ISBN, class: 'form-control' %>

	  <%= f.label :publish_date %>
	  <%= f.datetime_select :publish_date, class: 'form-control' %>

	  <%= f.submit "Save changes", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<%= will_paginate %>

<ul class="books">

  <% @books.each do |book| %>
    <%= render book%>
  <% end %>
</ul>
<%= will_paginate %>

<%if logged_in?%>

	<%= link_to 'New Book', new_book_path %>
<%end%>

app/views/books/new.html.erb
<% provide(:button_text, 'Create new book') %>
<h1>New Book</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.ISBN %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @book.publish_date %>
</p>
	<strong>Authors: </strong>
	<% @authors=@book.authors.all%>
	<% @authors.each do |author| %>
    	<%= author.name %> </br>
	<%end %>
<p>
</p>

<%if logged_in?%>
	<%= link_to 'Edit', edit_book_path(@book) %> |
<%end%>
<%= link_to 'Back', books_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <%= link_to "Book Store", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Search",    search_path %></li>
        <% if !logged_in? %>
        	<li><%= link_to "Admin",    login_path %></li>
        <%else%>
        	<li><%= link_to "Log Out",    logout_path, method: :delete %></li>
        <%end%>
      </ul>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header'%>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_search.html.erb
<% if @book_items.any? %>
  <ol class="microposts">
    <%= render @book_items %>
  </ol>
  <%= will_paginate @book_items %>
<% end %>